### ISSUE TITLE
RuntimeVersion and NativeVersion

### ISSUE THREAD

**Issue by SHA888** [debionetwork/debio-node#28]
@kevinjanada What is the difference between sp_version::RuntimeVersion and sp_vesion::NativeVersion implementation? When I refactor #[cfg(feature = "std"] and run Cargo Check, it says they are referring to the same thing
 
https://github.com/Degenics/debio-node/blob/ae72aaeec41937608249a8c3d5f2bda399a26a68/runtime/src/lib.rs#L22

Regarding this doc https://substrate.dev/rustdocs/v3.0.0/sp_version/struct.NativeVersion.html
this statement 
https://github.com/Degenics/debio-node/blob/ae72aaeec41937608249a8c3d5f2bda399a26a68/runtime/src/lib.rs#L137
should be like 
`pub struct NativeVersion {
    pub runtime_version: RuntimeVersion,
    ---
}`
Am I understand it correctly or I missed something here?
Thank you for the clarification

**Comment by kevinjanada** [comment]
I have not gone deeply into this yet, but from what i know, the runtime that is usually compiled into WASM, can also be compiled into native binary (i have not tested this).
sp_version::RuntimeVersion is used to define the version of the runtime when compiled to WASM.

pub struct NativeVersion is used to define the version when compiled to native binary. 
Note the #[cfg(feature = "std")] attribute which tells the compiler to use NativeVersion when std feature is available, which is when the runtime is compiled to native binary.

**Comment by kevinjanada** [comment]
Is this causing any problem when compiling?

**Comment by SHA888** [comment]
Yes, when I tried to refactor or reorder, it causes an issue saying they are the same.

**Comment by kevinjanada** [comment]
i see, could you elaborate on the purpose of the refactor, and a snippet of the code?

**Comment by SHA888** [comment]
Sure. I'd like to refactor to avoid the same code written repeatedly. Is it okay if I create a branch and push my code on the new branch so you could also test it?

**Comment by SHA888** [comment]
> I have not gone deeply into this yet, but from what i know, the runtime that is usually compiled into WASM, can also be compiled into native binary (i have not tested this).
> sp_version::RuntimeVersion is used to define the version of the runtime when compiled to WASM.
> 
> pub struct NativeVersion is used to define the version when compiled to native binary.
> Note the #[cfg(feature = "std")] attribute which tells the compiler to use NativeVersion when std feature is available, which is when the runtime is compiled to native binary.

Thank you mas @kevinjanada I found the solution after re-read Substrate architecture as your guidance regarding Wasm Runtime and Native Runtime. I was confused about the keywords NativeVersion and RuntimeVersion (which is refering to Wasm Runtime). 

I'll push it to branch and make PR so you could take a look as well.
