### ISSUE TITLE
refund_order extrinsic is calling fulfill_order in its implementation

### ISSUE THREAD

**Issue by kevinjanada** [debionetwork/debio-node#39]
**Description**
refund_order extrinsic is calling the wrong function in its implementation. 

**Steps to Reproduce**
make a refund_order extrinsic using polkadot.js/apps

**Expected vs. Actual Behavior**
Expected:
It should update the Order.status to OrderStatus::Refunded.
Event::OrderRefunded should be emitted

Actual:
It calls fulfill_order function.
error.UnauthorizedOrderFulfillment is emitted

**Comment by SHA888** [comment]
Okay I'll try it locally
