### ISSUE TITLE
Change OrderStatus::Success to OrderStatus::Fulfilled

### ISSUE THREAD

**Issue by kevinjanada** [debionetwork/debio-node#40]
**Motivation**
There seems to be confusion about the naming of OrderStatus::Success.
Currently it means that the Order has been successfully processed and the DnaSample result has been submitted.
Some people seem to think OrderStatus::Success to mean that the Order has been successfully created.

**Suggested Solution**
Change OrderStatus::Success to OrderStatus::Fulfilled

wdyt?
@SHA888 @agustinustheo

**Comment by SHA888** [comment]
@kevinjanada I think it's a good idea
